[framework]
name = "swoole"

[main]
dockerfile = "swoole.dockerfile"
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[sync-mysql]
dockerfile = "swoole-sync-mysql.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[async-pgsql]
dockerfile = "swoole-async-pgsql.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[async-mysql]
dockerfile = "swoole-async-mysql.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"
