[framework]
name = "swoole"

[main]
dockerfile = "swoole-sync-mysql.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[text]
dockerfile = "swoole.dockerfile"
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[no-async]
dockerfile = "swoole-async-mysql.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[postgres]
dockerfile = "swoole-sync-postgres.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"

[async-postgres]
dockerfile = "swoole-async-postgres.dockerfile"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "swoole"
webserver = "none"
versus = "php"
